#
# SPDX-License-Identifier:	GPL-2.0+
#

ifdef CONFIG_SPL_BUILD
obj-y += emi.o
obj-y += dramc_pi_basic_api.o
obj-y += dramc_pi_calibration_api.o
obj-y += dramc_pi_main.o
obj-y += hal_io.o
endif

#$(warning ====================================================================)
#$(warning $(SRCTREE))
#$(warning $(OBJTREE))
#$(warning $(UBOOTINCLUDE))
#$(warning $(ARCH))
#$(warning $(BOARD))
#$(warning ====================================================================)
